### ISSUE TITLE
To-do before May 6

### ISSUE THREAD

**Issue by iliana** [spaceboats/whiteboard#1]
[May 6 is the big day!](https://github.com/ku-eecs-capstone/blackboard/wiki/Landing-Plan)

Here's a giant checklist of shit we need to get done before then. I'm going to list all the things I need to get done, plus things I'm pretty sure we should get done for the presentation day. Each subproject team needs to comment with the things they need to do.
# busbus core
- [x] Merge `no-external-test-deps` (spaceboats/busbus#19)
- [x] ~~Add `busbus.Arrival.headway` support + test cases~~ (MBTA doesn't require this after all)
- [x] Add test cases for MBTA static data (spaceboats/busbus@7d090b22eb1f4aa841207a3940ce485b8539af5c)
- [x] Add MBTA realtime data
- [ ] Get setuptools entry points working for out-of-tree providers
- [ ] Write out-of-tree MV Transit realtime provider
- [ ] Make README.md clearer (spaceboats/busbus#5)
- [x] ~~Write API documentation~~ can wait until after May 6
- [ ] Add providers (with realtime if possible) (**providers crossed out were nixed evening of May 3**):
  - [x] ~~SF Bay Area:~~
    - [x] ~~BART~~
    - [x] ~~Caltrain~~
    - [x] ~~Muni~~
  - [x] ~~Seattle metro area:~~
    - [x] ~~Sound Transit~~
    - [x] ~~Seattle Streetcar Network (NextBus)~~
    - [x] ~~King Country Metro~~
  - [ ] KCATA
  - [x] ~~Transport for London~~
  - [ ] Tokyo Metro
# busbus web
- [x] ~~Determine if spaceboats/busbus#16 is resolved with `gtfs-rewrite`~~ can wait
- [x] ~~Write API documentation~~ can wait
- [x] ~~Write deployment documentation~~ can wait
# busbus web sample
- [x] ~~Ensure everything is still working once new data/agencies are enabled in busbus~~
- [x] ~~Add cancel button after searching for agency.~~
- [x] ~~Error checking on user input~~
- [x] ~~When cancel button is pressed and new agency is selected, old agencies info is still shown upon search.~~
  - [x] ~~Time options are also duplicated without removing originals in their dropdown boxes.~~
- [x] ~~Update appearance of alert boxes.~~
- [x] ~~Add some indication that loading is occurring instead of having dropdown boxes appear unpopulated for a short time.~~
- [x] ~~Completely update 'datastream' since provider id and route/stop need to be selected for query.~~
- [x] ~~Make sure 'datastream' will refresh table of results properly.~~
#3001-ledboard

File specific issues on the spaceboats/3001-ledboard repo
- [x] May 6 issues fixed
# Class presentation
- [x] Presentation outline
  - [x] Determine who is going to say what
- [x] Find a non-terrible HTML presentation framework
- [x] Create [asciinema](https://asciinema.org/) demo of busbus core + IPython
# Quadchart
- [x] ~~Find problems with quadchart and file issues~~
- [x] Fix all issues
- [x] Remove "DRAFT DO NOT PRINT" text
- [x] Generate PDF, send to Andy/Omar
# Blag
- [ ] Write end-of-semester blog post for busbus core and web
- [x] Android app blog post portion
- [x] ~~Web app blog post portion~~

**Comment by iliana** [comment]
May 6 has come and gone so I'm closing this issue. :)
